# Generated by Django 3.0.2 on 2020-01-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200113_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='age',
        ),
        migrations.AddField(
            model_name='employees',
            name='dob',
            field=models.DateTimeField(default=None),
        ),
    ]
